[project]
name = "ingest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "mainStorne", email = "dbevzpr@mail.ru" }]
requires-python = ">=3.14"
dependencies = [
    "langchain-community>=0.4.2",
    "langchain-text-splitters>=1.1.2",
    "pymongo>=4.18.1",
    "pymupdf>=1.28.2",
    "pymupdf4llm>=1.28.2",
]
