/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as PreviewsIndexRouteImport } from './routes/previews/index';
import { Route as PreviewsTableRouteImport } from './routes/previews/table';
import { Route as PreviewsButtonsRouteImport } from './routes/previews/buttons';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const PreviewsIndexRoute = PreviewsIndexRouteImport.update({
  id: '/previews/',
  path: '/previews/',
  getParentRoute: () => rootRouteImport,
} as any);
const PreviewsTableRoute = PreviewsTableRouteImport.update({
  id: '/previews/table',
  path: '/previews/table',
  getParentRoute: () => rootRouteImport,
} as any);
const PreviewsButtonsRoute = PreviewsButtonsRouteImport.update({
  id: '/previews/buttons',
  path: '/previews/buttons',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/previews/buttons': typeof PreviewsButtonsRoute;
  '/previews/table': typeof PreviewsTableRoute;
  '/previews': typeof PreviewsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/previews/buttons': typeof PreviewsButtonsRoute;
  '/previews/table': typeof PreviewsTableRoute;
  '/previews': typeof PreviewsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/previews/buttons': typeof PreviewsButtonsRoute;
  '/previews/table': typeof PreviewsTableRoute;
  '/previews/': typeof PreviewsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/previews/buttons' | '/previews/table' | '/previews';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/previews/buttons' | '/previews/table' | '/previews';
  id: '__root__' | '/' | '/previews/buttons' | '/previews/table' | '/previews/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PreviewsButtonsRoute: typeof PreviewsButtonsRoute;
  PreviewsTableRoute: typeof PreviewsTableRoute;
  PreviewsIndexRoute: typeof PreviewsIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/previews/': {
      id: '/previews/';
      path: '/previews';
      fullPath: '/previews';
      preLoaderRoute: typeof PreviewsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/previews/table': {
      id: '/previews/table';
      path: '/previews/table';
      fullPath: '/previews/table';
      preLoaderRoute: typeof PreviewsTableRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/previews/buttons': {
      id: '/previews/buttons';
      path: '/previews/buttons';
      fullPath: '/previews/buttons';
      preLoaderRoute: typeof PreviewsButtonsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewsButtonsRoute: PreviewsButtonsRoute,
  PreviewsTableRoute: PreviewsTableRoute,
  PreviewsIndexRoute: PreviewsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
