name: innosport

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8082:80"
    restart: unless-stopped

  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    depends_on:
      database:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SETTINGS_PATH: /app/settings.docker.yaml
    ports:
      - "8000:8000"
    volumes:
      - ./backend/settings.docker.yaml:/app/settings.docker.yaml:ro
    restart: unless-stopped

  database:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval 'quit(db.adminCommand({ ping: 1 }).ok ? 0 : 1)'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

volumes:
  mongodb:
