name: innosport

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8082:80"
    restart: unless-stopped

  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    depends_on:
      database:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SETTINGS_PATH: /app/settings.docker.yaml
    ports:
      - "8000:8000"
    volumes:
      - ./backend/settings.docker.yaml:/app/settings.docker.yaml:ro
      - ./data/sample_queries.txt:/data/sample_queries.txt:ro
    restart: unless-stopped

  database:
    image: mongodb/mongodb-atlas-local:latest
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME:-mongoadmin}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD:-secret}
    restart: unless-stopped

volumes:
  db:
  config:
