# This is a Docker Compose configuration for local use.

# Run all services:
# docker compose up --build --wait

services:
  api:
    build: .
    restart: no
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro" # Read-only settings file
      - "../data/sample_queries.txt:/data/sample_queries.txt:ro"
    deploy:
      # Change limits if project needs more RAM, though try to stay within limits
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 500m

  db:
    image: mongodb/mongodb-atlas-local:latest
    restart: no
    ports:
      - "27017:27017"
    volumes:
      - "db:/data/db"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME:-mongoadmin}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD:-secret}

volumes:
  db:
