/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dialogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dialogs */
        get: operations["list_dialogs_dialogs_get"];
        put?: never;
        /** Create Dialog */
        post: operations["create_dialog_dialogs_post"];
        /** Delete Dialogs */
        delete: operations["delete_dialogs_dialogs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dialog Analytics */
        get: operations["get_dialog_analytics_dialogs_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/{dialog_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dialog */
        get: operations["get_dialog_dialogs__dialog_id__get"];
        put?: never;
        post?: never;
        /** Delete Dialog */
        delete: operations["delete_dialog_dialogs__dialog_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/{dialog_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dialog Summary */
        get: operations["get_dialog_summary_dialogs__dialog_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/{dialog_id}/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dialog Classification */
        get: operations["get_dialog_classification_dialogs__dialog_id__classification_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/{dialog_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Dialog */
        post: operations["close_dialog_dialogs__dialog_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/{dialog_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Submit Feedback */
        put: operations["submit_feedback_dialogs__dialog_id__feedback_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/{dialog_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Message */
        post: operations["post_message_dialogs__dialog_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/{dialog_id}/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Message */
        post: operations["stream_message_dialogs__dialog_id__messages_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/{dialog_id}/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Specialist
         * @description Save contact details and hand the appeal to the selected specialist line.
         */
        post: operations["request_specialist_dialogs__dialog_id__escalate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audits/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Audit Email
         * @description Generate and email an audit of feedback saved in the last 24 hours.
         */
        post: operations["send_audit_email_admin_audits_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Audit
         * @description Analyze a supplied sample of rated dialogs without truncating their transcripts.
         */
        post: operations["create_audit_admin_audits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsBucket */
        AnalyticsBucket: {
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** AnalyticsDay */
        AnalyticsDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Total */
            total: number;
            /** Escalated */
            escalated: number;
        };
        /** AuditDialog */
        AuditDialog: {
            /** Id */
            id: string;
            /** Messages */
            messages: components["schemas"]["AuditMessage"][];
            feedback: components["schemas"]["AuditFeedback"];
        };
        /** AuditEmailResponse */
        AuditEmailResponse: {
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /** Dialog Count */
            dialog_count: number;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
        };
        /** AuditFeedback */
        AuditFeedback: {
            /**
             * Rating
             * @enum {string}
             */
            rating: "complete" | "partial" | "irrelevant";
            /**
             * Comment
             * @default
             */
            comment: string;
        };
        /** AuditMessage */
        AuditMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** AuditRatings */
        AuditRatings: {
            /** Complete */
            complete: number;
            /** Partial */
            partial: number;
            /** Irrelevant */
            irrelevant: number;
        };
        /** AuditRequest */
        AuditRequest: {
            /** Dialogs */
            dialogs: components["schemas"]["AuditDialog"][];
        };
        /** AuditResponse */
        AuditResponse: {
            /** Analysis */
            analysis: string;
            /** Dialog Ids */
            dialog_ids: string[];
            ratings: components["schemas"]["AuditRatings"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** Citation */
        Citation: {
            /** Document */
            document: string;
            /** Section */
            section: string;
            /** Path */
            path: string;
        };
        /** Clarification */
        Clarification: {
            /** Question */
            question: string;
            /** Options */
            options: string[];
            /** Id */
            id: string;
        };
        /** DialogAnalytics */
        DialogAnalytics: {
            /** Days */
            days: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Total Closed */
            total_closed: number;
            /** Analyzed */
            analyzed: number;
            /** Pending */
            pending: number;
            /** Classified */
            classified: number;
            /** With Remaining Questions */
            with_remaining_questions: number;
            /** Summarized */
            summarized: number;
            /** Rated */
            rated: number;
            /** Complete Ratings */
            complete_ratings: number;
            /** Daily */
            daily: components["schemas"]["AnalyticsDay"][];
            /** Topics */
            topics: components["schemas"]["AnalyticsBucket"][];
            /** Subtopics */
            subtopics: components["schemas"]["AnalyticsBucket"][];
            /** Outcomes */
            outcomes: components["schemas"]["AnalyticsBucket"][];
            /** Ratings */
            ratings: components["schemas"]["AnalyticsBucket"][];
        };
        /** DialogClassification */
        DialogClassification: {
            /** Subtopic Id */
            subtopic_id: string | null;
            /** Reason */
            reason: string;
            /** Topic */
            topic: string | null;
            /** Subtopic */
            subtopic: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Dialog Updated At */
            dialog_updated_at: string | null;
        };
        /** DialogDeleteResult */
        DialogDeleteResult: {
            /** Deleted */
            deleted: number;
        };
        /** DialogFeedback */
        DialogFeedback: {
            /**
             * Rating
             * @enum {string}
             */
            rating: "complete" | "partial" | "irrelevant";
            /**
             * Comment
             * @default
             */
            comment: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /** DialogFeedbackCreate */
        DialogFeedbackCreate: {
            /**
             * Rating
             * @enum {string}
             */
            rating: "complete" | "partial" | "irrelevant";
            /**
             * Comment
             * @default
             */
            comment: string;
        };
        /** DialogListItem */
        DialogListItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Preview
             * @default
             */
            preview: string;
            status?: components["schemas"]["DialogStatus"] | null;
            line?: components["schemas"]["SupportLine"] | null;
            /**
             * Closed
             * @default false
             */
            closed: boolean;
            /** Reason */
            reason?: string | null;
            feedback?: components["schemas"]["DialogFeedback"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DialogMessage */
        DialogMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            clarification?: components["schemas"]["Clarification"] | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][];
        };
        /** DialogResponse */
        DialogResponse: {
            /** Id */
            id: string;
            /** Reply */
            reply: string;
            clarification?: components["schemas"]["Clarification"] | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][];
            status?: components["schemas"]["DialogStatus"] | null;
            line?: components["schemas"]["SupportLine"] | null;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /**
             * Closed
             * @default false
             */
            closed: boolean;
            /** Reason */
            reason?: string | null;
            feedback?: components["schemas"]["DialogFeedback"] | null;
            specialist_contact?: components["schemas"]["SpecialistContact"] | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * DialogStatus
         * @enum {string}
         */
        DialogStatus: "clarifying" | "answered" | "escalate" | "closed_abuse";
        /** DialogStreamEvent */
        DialogStreamEvent: {
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "tool" | "done" | "error";
            /**
             * Text
             * @default
             */
            text: string;
            tool_call?: components["schemas"]["ToolCall"] | null;
            status?: components["schemas"]["ToolStatus"] | null;
            response?: components["schemas"]["DialogResponse"] | null;
            /** Detail */
            detail?: string | null;
        };
        /** DialogSummary */
        DialogSummary: {
            /** User Request */
            user_request: string;
            /** Remaining Questions */
            remaining_questions: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Dialog Updated At */
            dialog_updated_at: string | null;
        };
        /** DialogView */
        DialogView: {
            /** Id */
            id: string;
            /** Reply */
            reply: string;
            clarification?: components["schemas"]["Clarification"] | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][];
            status?: components["schemas"]["DialogStatus"] | null;
            line?: components["schemas"]["SupportLine"] | null;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /**
             * Closed
             * @default false
             */
            closed: boolean;
            /** Reason */
            reason?: string | null;
            feedback?: components["schemas"]["DialogFeedback"] | null;
            specialist_contact?: components["schemas"]["SpecialistContact"] | null;
            /** Updated At */
            updated_at?: string | null;
            /** Messages */
            messages?: components["schemas"]["DialogMessage"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageCreate */
        MessageCreate: {
            /** Content */
            content: string;
            /** Clarification Id */
            clarification_id?: string | null;
        };
        /** SpecialistContact */
        SpecialistContact: {
            /** Inn */
            inn: string;
            /** Organization Name */
            organization_name: string;
            /**
             * Contact Email
             * Format: email
             */
            contact_email: string;
        };
        /**
         * SupportLine
         * @enum {string}
         */
        SupportLine: "L1" | "L2" | "L3";
        /** ToolCall */
        ToolCall: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        ToolStatus: "preparing" | "running" | "completed" | "error" | "awaiting_user";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAnalyticsBucket = components['schemas']['AnalyticsBucket'];
export type SchemaAnalyticsDay = components['schemas']['AnalyticsDay'];
export type SchemaAuditDialog = components['schemas']['AuditDialog'];
export type SchemaAuditEmailResponse = components['schemas']['AuditEmailResponse'];
export type SchemaAuditFeedback = components['schemas']['AuditFeedback'];
export type SchemaAuditMessage = components['schemas']['AuditMessage'];
export type SchemaAuditRatings = components['schemas']['AuditRatings'];
export type SchemaAuditRequest = components['schemas']['AuditRequest'];
export type SchemaAuditResponse = components['schemas']['AuditResponse'];
export type SchemaCitation = components['schemas']['Citation'];
export type SchemaClarification = components['schemas']['Clarification'];
export type SchemaDialogAnalytics = components['schemas']['DialogAnalytics'];
export type SchemaDialogClassification = components['schemas']['DialogClassification'];
export type SchemaDialogDeleteResult = components['schemas']['DialogDeleteResult'];
export type SchemaDialogFeedback = components['schemas']['DialogFeedback'];
export type SchemaDialogFeedbackCreate = components['schemas']['DialogFeedbackCreate'];
export type SchemaDialogListItem = components['schemas']['DialogListItem'];
export type SchemaDialogMessage = components['schemas']['DialogMessage'];
export type SchemaDialogResponse = components['schemas']['DialogResponse'];
export type SchemaDialogStatus = components['schemas']['DialogStatus'];
export type SchemaDialogStreamEvent = components['schemas']['DialogStreamEvent'];
export type SchemaDialogSummary = components['schemas']['DialogSummary'];
export type SchemaDialogView = components['schemas']['DialogView'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaMessageCreate = components['schemas']['MessageCreate'];
export type SchemaSpecialistContact = components['schemas']['SpecialistContact'];
export type SchemaSupportLine = components['schemas']['SupportLine'];
export type SchemaToolCall = components['schemas']['ToolCall'];
export type SchemaToolStatus = components['schemas']['ToolStatus'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    list_dialogs_dialogs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dialog_dialogs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogView"];
                };
            };
        };
    };
    delete_dialogs_dialogs_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogDeleteResult"];
                };
            };
        };
    };
    get_dialog_analytics_dialogs_analytics_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogAnalytics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dialog_dialogs__dialog_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dialog_dialogs__dialog_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogDeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dialog_summary_dialogs__dialog_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dialog_classification_dialogs__dialog_id__classification_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogClassification"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_dialog_dialogs__dialog_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_dialogs__dialog_id__feedback_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DialogFeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogFeedback"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_dialogs__dialog_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_message_dialogs__dialog_id__messages_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description NDJSON events: provisional text, tool execution statuses, then a saved response or an error. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["DialogStreamEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_specialist_dialogs__dialog_id__escalate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecialistContact"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_audit_email_admin_audits_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEmailResponse"];
                };
            };
        };
    };
    create_audit_admin_audits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
