/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dialogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dialogs */
        get: operations["list_dialogs_dialogs_get"];
        put?: never;
        /** Create Dialog */
        post: operations["create_dialog_dialogs_post"];
        /** Delete Dialogs */
        delete: operations["delete_dialogs_dialogs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/{dialog_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dialog */
        get: operations["get_dialog_dialogs__dialog_id__get"];
        put?: never;
        post?: never;
        /** Delete Dialog */
        delete: operations["delete_dialog_dialogs__dialog_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/{dialog_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Message */
        post: operations["post_message_dialogs__dialog_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/{dialog_id}/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Message */
        post: operations["stream_message_dialogs__dialog_id__messages_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dialogs/{dialog_id}/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Specialist
         * @description Select a specialist; only this action determines L1 versus L2.
         */
        post: operations["request_specialist_dialogs__dialog_id__escalate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Citation */
        Citation: {
            /** Document */
            document: string;
            /** Section */
            section: string;
            /** Path */
            path: string;
        };
        /** Clarification */
        Clarification: {
            /** Question */
            question: string;
            /** Options */
            options: string[];
            /** Id */
            id: string;
        };
        /** DialogDeleteResult */
        DialogDeleteResult: {
            /** Deleted */
            deleted: number;
        };
        /** DialogListItem */
        DialogListItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Preview
             * @default
             */
            preview: string;
            status?: components["schemas"]["DialogStatus"] | null;
            line?: components["schemas"]["SupportLine"] | null;
            /**
             * Closed
             * @default false
             */
            closed: boolean;
            /** Reason */
            reason?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DialogMessage */
        DialogMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            clarification?: components["schemas"]["Clarification"] | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][];
        };
        /** DialogResponse */
        DialogResponse: {
            /** Id */
            id: string;
            /** Reply */
            reply: string;
            clarification?: components["schemas"]["Clarification"] | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][];
            status?: components["schemas"]["DialogStatus"] | null;
            line?: components["schemas"]["SupportLine"] | null;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /**
             * Closed
             * @default false
             */
            closed: boolean;
            /** Reason */
            reason?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * DialogStatus
         * @enum {string}
         */
        DialogStatus: "clarifying" | "answered" | "escalate" | "closed_abuse";
        /** DialogStreamEvent */
        DialogStreamEvent: {
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "tool" | "done" | "error";
            /**
             * Text
             * @default
             */
            text: string;
            tool_call?: components["schemas"]["ToolCall"] | null;
            status?: components["schemas"]["ToolStatus"] | null;
            response?: components["schemas"]["DialogResponse"] | null;
            /** Detail */
            detail?: string | null;
        };
        /** DialogView */
        DialogView: {
            /** Id */
            id: string;
            /** Reply */
            reply: string;
            clarification?: components["schemas"]["Clarification"] | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][];
            status?: components["schemas"]["DialogStatus"] | null;
            line?: components["schemas"]["SupportLine"] | null;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /**
             * Closed
             * @default false
             */
            closed: boolean;
            /** Reason */
            reason?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Messages */
            messages?: components["schemas"]["DialogMessage"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageCreate */
        MessageCreate: {
            /** Content */
            content: string;
            /** Clarification Id */
            clarification_id?: string | null;
        };
        /**
         * SupportLine
         * @enum {string}
         */
        SupportLine: "L1" | "L2" | "L3";
        /** ToolCall */
        ToolCall: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        ToolStatus: "preparing" | "running" | "completed" | "error" | "awaiting_user";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaCitation = components['schemas']['Citation'];
export type SchemaClarification = components['schemas']['Clarification'];
export type SchemaDialogDeleteResult = components['schemas']['DialogDeleteResult'];
export type SchemaDialogListItem = components['schemas']['DialogListItem'];
export type SchemaDialogMessage = components['schemas']['DialogMessage'];
export type SchemaDialogResponse = components['schemas']['DialogResponse'];
export type SchemaDialogStatus = components['schemas']['DialogStatus'];
export type SchemaDialogStreamEvent = components['schemas']['DialogStreamEvent'];
export type SchemaDialogView = components['schemas']['DialogView'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaMessageCreate = components['schemas']['MessageCreate'];
export type SchemaSupportLine = components['schemas']['SupportLine'];
export type SchemaToolCall = components['schemas']['ToolCall'];
export type SchemaToolStatus = components['schemas']['ToolStatus'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    list_dialogs_dialogs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dialog_dialogs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogView"];
                };
            };
        };
    };
    delete_dialogs_dialogs_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogDeleteResult"];
                };
            };
        };
    };
    get_dialog_dialogs__dialog_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dialog_dialogs__dialog_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogDeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_dialogs__dialog_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_message_dialogs__dialog_id__messages_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description NDJSON events: provisional text, tool execution statuses, then a saved response or an error. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["DialogStreamEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_specialist_dialogs__dialog_id__escalate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialog_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
