/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ChatTicketsDialogIdRouteImport } from './routes/_chat.tickets.$dialogId'
import { Route as AdminTicketsDialogIdRouteImport } from './routes/admin.tickets.$dialogId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ChatTicketsDialogIdRoute = ChatTicketsDialogIdRouteImport.update({
  id: '/tickets/$dialogId',
  path: '/tickets/$dialogId',
  getParentRoute: () => ChatRoute,
} as any)
const AdminTicketsDialogIdRoute = AdminTicketsDialogIdRouteImport.update({
  id: '/tickets/$dialogId',
  path: '/tickets/$dialogId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/': typeof AdminIndexRoute
  '/tickets/$dialogId': typeof ChatTicketsDialogIdRoute
  '/admin/tickets/$dialogId': typeof AdminTicketsDialogIdRoute
}
export interface FileRoutesByTo {
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/': typeof ChatIndexRoute
  '/admin': typeof AdminIndexRoute
  '/tickets/$dialogId': typeof ChatTicketsDialogIdRoute
  '/admin/tickets/$dialogId': typeof AdminTicketsDialogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/_chat/': typeof ChatIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_chat/tickets/$dialogId': typeof ChatTicketsDialogIdRoute
  '/admin/tickets/$dialogId': typeof AdminTicketsDialogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/'
    | '/tickets/$dialogId'
    | '/admin/tickets/$dialogId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/analytics'
    | '/admin/audit'
    | '/'
    | '/admin'
    | '/tickets/$dialogId'
    | '/admin/tickets/$dialogId'
  id:
    | '__root__'
    | '/_chat'
    | '/admin'
    | '/admin/analytics'
    | '/admin/audit'
    | '/_chat/'
    | '/admin/'
    | '/_chat/tickets/$dialogId'
    | '/admin/tickets/$dialogId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_chat/tickets/$dialogId': {
      id: '/_chat/tickets/$dialogId'
      path: '/tickets/$dialogId'
      fullPath: '/tickets/$dialogId'
      preLoaderRoute: typeof ChatTicketsDialogIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/admin/tickets/$dialogId': {
      id: '/admin/tickets/$dialogId'
      path: '/tickets/$dialogId'
      fullPath: '/admin/tickets/$dialogId'
      preLoaderRoute: typeof AdminTicketsDialogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatTicketsDialogIdRoute: typeof ChatTicketsDialogIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatTicketsDialogIdRoute: ChatTicketsDialogIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTicketsDialogIdRoute: typeof AdminTicketsDialogIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTicketsDialogIdRoute: AdminTicketsDialogIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
